import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FontWrapper from "./components/FontWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <FontWrapper geistSansVar={geistSans.variable} geistMonoVar={geistMono.variable}>
        {children}
      </FontWrapper>
    </html>
  );
}
